sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start Creating an image with dockerfile"
    - docker build -t miny1981/docker-react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true miny1981/docker-react-app npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "docker-react-app"
    env: "DockerReactApp-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-812999597073"
    bucket_path: "docker-react-app"
    on:
        branch: main

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY


